export const NATIONALITY_PT_TO_ISO: Record<string, string> = {
  Alemanha: "GER",
  "Alemanha Oriental": "GDR",
  Argentina: "ARG",
  "Argentina/Espanha": "ARG",
  "Argentina/Itália": "ARG",
  Argélia: "ALG",
  Armênia: "ARM",
  Austrália: "AUS",
  Brasil: "BRA",
  "Brasil/Espanha": "BRA",
  "Brasil/Itália": "BRA",
  Bulgária: "BUL",
  Bélgica: "BEL",
  "Bósnia e Herzegovina": "BIH",
  Camarões: "CMR",
  Canadá: "CAN",
  Chade: "CHA",
  Chile: "CHI",
  Colômbia: "COL",
  "Coreia do Sul": "KOR",
  "Costa Rica": "CRC",
  "Costa do Marfim": "CIV",
  Croácia: "CRO",
  Dinamarca: "DEN",
  Egito: "EGY",
  Escócia: "SCO",
  Eslováquia: "SVK",
  Eslovênia: "SVN",
  Espanha: "ESP",
  "Estados Unidos": "USA",
  "Filipinas/Espanha": "PHI",
  Finlândia: "FIN",
  França: "FRA",
  Gabão: "GAB",
  Gana: "GHA",
  Geórgia: "GEO",
  Guiné: "GUI",
  Hungria: "HUN",
  "Hungria/Espanha": "HUN",
  Inglaterra: "ENG",
  Irlanda: "IRL",
  "Irlanda do Norte": "NIR",
  Itália: "ITA",
  Japão: "JPN",
  Libéria: "LBR",
  "Macedônia do Norte": "MKD",
  Mali: "MLI",
  Marrocos: "MAR",
  Montenegro: "MNE",
  México: "MEX",
  Nigéria: "NGA",
  Noruega: "NOR",
  "Nova Zelândia": "NZL",
  Paraguai: "PAR",
  "País de Gales": "WAL",
  "Países Baixos": "NED",
  Peru: "PER",
  Polônia: "POL",
  Portugal: "POR",
  "República Democrática do Congo": "COD",
  "República Tcheca": "CZE",
  Rússia: "RUS",
  Senegal: "SEN",
  Suécia: "SWE",
  Suíça: "SUI",
  Sérvia: "SRB",
  Togo: "TOG",
  "Trinidad e Tobago": "TRI",
  Tunísia: "TUN",
  Turquia: "TUR",
  Ucrânia: "UKR",
  Uruguai: "URU",
  "Uruguai/Espanha": "URU",
  Venezuela: "VEN",
  Zimbábue: "ZIM",
  "África do Sul": "RSA",
  Áustria: "AUT",
};

export const FILTER_NATIONALITIES: { value: string; label: string }[] = [
  { value: "BRA", label: "Brasil" },
  { value: "FRA", label: "França" },
  { value: "GER", label: "Alemanha" },
  { value: "ESP", label: "Espanha" },
  { value: "ITA", label: "Itália" },
  { value: "ENG", label: "Inglaterra" },
  { value: "NED", label: "Países Baixos" },
  { value: "BEL", label: "Bélgica" },
  { value: "URU", label: "Uruguai" },
  { value: "POR", label: "Portugal" },
  { value: "ARG", label: "Argentina" },
  { value: "SRB", label: "Sérvia" },
  { value: "COL", label: "Colômbia" },
  { value: "CRO", label: "Croácia" },
  { value: "CIV", label: "Costa do Marfim" },
  { value: "BIH", label: "Bósnia e Herzegovina" },
  { value: "SWE", label: "Suécia" },
  { value: "MEX", label: "México" },
  { value: "SEN", label: "Senegal" },
  { value: "TUR", label: "Turquia" },
  { value: "CHI", label: "Chile" },
  { value: "NGA", label: "Nigéria" },
  { value: "POL", label: "Polônia" },
  { value: "CZE", label: "República Tcheca" },
  { value: "SUI", label: "Suíça" },
  { value: "DEN", label: "Dinamarca" },
  { value: "SCO", label: "Escócia" },
  { value: "WAL", label: "País de Gales" },
];

export function mapNationalityToIso(nationalityPt: string): string {
  const direct = NATIONALITY_PT_TO_ISO[nationalityPt.trim()];
  if (direct) return direct;

  const first = nationalityPt.split("/")[0]?.trim();
  if (first && NATIONALITY_PT_TO_ISO[first]) {
    return NATIONALITY_PT_TO_ISO[first];
  }

  return "UNK";
}

export function isoToLabel(iso: string): string {
  const match = FILTER_NATIONALITIES.find((n) => n.value === iso);
  return match?.label ?? iso;
}

const ISO_TO_CONTINENT: Record<string, string> = {
  ALG: "África",
  CMR: "África",
  CHA: "África",
  CIV: "África",
  COD: "África",
  EGY: "África",
  GAB: "África",
  GHA: "África",
  GUI: "África",
  LBR: "África",
  MLI: "África",
  MAR: "África",
  NGA: "África",
  RSA: "África",
  SEN: "África",
  TOG: "África",
  TUN: "África",
  ZIM: "África",
  ARM: "Ásia",
  KOR: "Ásia",
  JPN: "Ásia",
  PHI: "Ásia",
  TUR: "Ásia",
  GEO: "Ásia",
  AUS: "Oceania",
  NZL: "Oceania",
  CAN: "América do Norte",
  CRC: "América do Norte",
  MEX: "América do Norte",
  USA: "América do Norte",
  TRI: "América do Norte",
  ARG: "América do Sul",
  BRA: "América do Sul",
  CHI: "América do Sul",
  COL: "América do Sul",
  PAR: "América do Sul",
  PER: "América do Sul",
  URU: "América do Sul",
  VEN: "América do Sul",
  AUT: "Europa",
  BEL: "Europa",
  BIH: "Europa",
  BUL: "Europa",
  CRO: "Europa",
  CZE: "Europa",
  DEN: "Europa",
  ENG: "Europa",
  ESP: "Europa",
  FIN: "Europa",
  FRA: "Europa",
  GDR: "Europa",
  GER: "Europa",
  HUN: "Europa",
  IRL: "Europa",
  ITA: "Europa",
  MKD: "Europa",
  MNE: "Europa",
  NED: "Europa",
  NIR: "Europa",
  NOR: "Europa",
  POL: "Europa",
  POR: "Europa",
  RUS: "Europa",
  SCO: "Europa",
  SRB: "Europa",
  SVK: "Europa",
  SVN: "Europa",
  SUI: "Europa",
  SWE: "Europa",
  UKR: "Europa",
  WAL: "Europa",
};

export function isoToContinent(iso: string): string {
  return ISO_TO_CONTINENT[iso] ?? "Desconhecido";
}

export function nationalitiesShareContinent(isos: string[]): boolean {
  if (isos.length === 0) return false;
  const continents = new Set(isos.map(isoToContinent));
  return continents.size === 1 && !continents.has("Desconhecido");
}
